### PR TITLE
Add ZYNQ7010

### PR DESCRIPTION
**Pull request by Anuo-shuo**

### CODE REVIEW

**Comment by Zepan** [comment]
你好，A9具有NEON加速指令，建议在tm_port.h开启NEON加速指令测试哦

**Comment by Anuo-shuo** [comment]
#define TM_ARCH         TM_ARCH_ARM_NEON
#define TM_OPT_LEVEL    TM_OPT0
#define TM_MDL_TYPE     TM_MDL_INT8

使用TM_ARCH_ARM_NEON出现编译错误：
 error: inlining failed in call to always_inline ‘vdupq_n_s32’: target specific option mismatch
 vdupq_n_s32 (int32_t __a)

**Comment by Anuo-shuo** [comment]
#define TM_ARCH                     TM_ARCH_ARM_NEON
#define TM_OPT_LEVEL             TM_OPT0
#define TM_MDL_TYPE              TM_MDL_INT8或TM_MDL_FP32
该配置下会编译错误：
In file included from /home/xilinx/tinymaix/TinyMaix/src/arch_arm_neon.h:18:0,
                 from /home/xilinx/tinymaix/TinyMaix/src/tm_layers.c:24:
/home/xilinx/tinymaix/TinyMaix/src/arch_arm_neon.h: In function ‘tm_dot_prod’:
/usr/lib/gcc/arm-linux-gnueabihf/7/include/arm_neon.h:6740:1: error: inlining failed in call to always_inline ‘vdupq_n_f32’: target specific option mismatch vdupq_n_f32 (float32_t __a)

**Comment by Anuo-shuo** [comment]
已添加NEON加速指令测试结果

**Pull request merged**
