### PR TITLE
add STM32L496

### PR DESCRIPTION
**Pull request by starry-m**

### CODE REVIEW

**Comment by Zepan** [comment]
hi, you forget commit the picture.  and please try O1 too

**Comment by starry-m** [comment]
ok,I will add it tomorrow.thanks!

**Comment by Zepan** [comment]
I see mbnet128 O0 is 12s, O1 is 0.8s, is there some mistake?

**Comment by starry-m** [comment]
Sorry, I chose the wrong optimization level in mdk！
I have changed it now.

**Pull request merged**
